-- ============================================================================
-- 新增 harmony_state 枚举值:PENDING_ADAPTATION(待适配)
--
-- 语义:分析后确认需要鸿蒙化适配,但目前尚未适配。
-- 是 NOT_ADAPTED(未适配/信号检测默认值)的细分:
--   - NOT_ADAPTED       = 未评估/信号检测默认(事实层面)
--   - PENDING_ADAPTATION = 分析后确认需要适配(结论层面,由 LLM/人工产出)
-- 两者在评分门控中 gate 均为 1.0(高优先级)。
--
-- 注意:ALTER TYPE ... ADD VALUE 必须在独立事务中提交,
--       同事务内立即引用新值会触发 "unsafe use of new value" 错误。
--       因此拆分为 0010(本文件:仅加枚举值) + 0011(视图重建)两步。
-- ============================================================================
alter type harmony_state add value if not exists 'PENDING_ADAPTATION';
